// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/PGS.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// indGen_cpp
List indGen_cpp(vec id_vect);
RcppExport SEXP PGS_indGen_cpp(SEXP id_vectSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< vec >::type id_vect(id_vectSEXP);
    __result = Rcpp::wrap(indGen_cpp(id_vect));
    return __result;
END_RCPP
}
// est_pgee_grid_cpp
List est_pgee_grid_cpp(vec y_vect, mat x_mat, vec id_vect, vec beta_hat_R, int fold, int p, vec lam_vect, double eps_stop, int iter_try, std::string corr_str);
RcppExport SEXP PGS_est_pgee_grid_cpp(SEXP y_vectSEXP, SEXP x_matSEXP, SEXP id_vectSEXP, SEXP beta_hat_RSEXP, SEXP foldSEXP, SEXP pSEXP, SEXP lam_vectSEXP, SEXP eps_stopSEXP, SEXP iter_trySEXP, SEXP corr_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< vec >::type y_vect(y_vectSEXP);
    Rcpp::traits::input_parameter< mat >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< vec >::type id_vect(id_vectSEXP);
    Rcpp::traits::input_parameter< vec >::type beta_hat_R(beta_hat_RSEXP);
    Rcpp::traits::input_parameter< int >::type fold(foldSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< vec >::type lam_vect(lam_vectSEXP);
    Rcpp::traits::input_parameter< double >::type eps_stop(eps_stopSEXP);
    Rcpp::traits::input_parameter< int >::type iter_try(iter_trySEXP);
    Rcpp::traits::input_parameter< std::string >::type corr_str(corr_strSEXP);
    __result = Rcpp::wrap(est_pgee_grid_cpp(y_vect, x_mat, id_vect, beta_hat_R, fold, p, lam_vect, eps_stop, iter_try, corr_str));
    return __result;
END_RCPP
}
// one_run_grid_cpp
List one_run_grid_cpp(vec y_vect, mat x_mat, vec id_vect, int fold, int p, vec lam_vect, double eps_stop, int iter_try, std::string corr_str);
RcppExport SEXP PGS_one_run_grid_cpp(SEXP y_vectSEXP, SEXP x_matSEXP, SEXP id_vectSEXP, SEXP foldSEXP, SEXP pSEXP, SEXP lam_vectSEXP, SEXP eps_stopSEXP, SEXP iter_trySEXP, SEXP corr_strSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< vec >::type y_vect(y_vectSEXP);
    Rcpp::traits::input_parameter< mat >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< vec >::type id_vect(id_vectSEXP);
    Rcpp::traits::input_parameter< int >::type fold(foldSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< vec >::type lam_vect(lam_vectSEXP);
    Rcpp::traits::input_parameter< double >::type eps_stop(eps_stopSEXP);
    Rcpp::traits::input_parameter< int >::type iter_try(iter_trySEXP);
    Rcpp::traits::input_parameter< std::string >::type corr_str(corr_strSEXP);
    __result = Rcpp::wrap(one_run_grid_cpp(y_vect, x_mat, id_vect, fold, p, lam_vect, eps_stop, iter_try, corr_str));
    return __result;
END_RCPP
}
