# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countRep_cpp <- function(id) {
    .Call('PGS_countRep_cpp', PACKAGE = 'PGS', id)
}

indGen_cpp <- function(id_vect) {
    .Call('PGS_indGen_cpp', PACKAGE = 'PGS', id_vect)
}

seqJoin_vec <- function(seq1, seq2, m) {
    .Call('PGS_seqJoin_vec', PACKAGE = 'PGS', seq1, seq2, m)
}

seqJoin_int <- function(seq, m) {
    .Call('PGS_seqJoin_int', PACKAGE = 'PGS', seq, m)
}

corr_est_normal_cpp <- function(y_vect, x_mat, id_vect, beta_val, p, corr_str) {
    .Call('PGS_corr_est_normal_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, beta_val, p, corr_str)
}

est_pgee_grid_cpp <- function(y_vect, x_mat, id_vect, beta_hat_R, fold, p, lam_vect, eps_stop, iter_try, corr_str) {
    .Call('PGS_est_pgee_grid_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, beta_hat_R, fold, p, lam_vect, eps_stop, iter_try, corr_str)
}

one_run_grid_cpp <- function(y_vect, x_mat, id_vect, fold, p, lam_vect, eps_stop, iter_try, corr_str) {
    .Call('PGS_one_run_grid_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, fold, p, lam_vect, eps_stop, iter_try, corr_str)
}

