# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

est_pgee_grid_cpp <- function(y_vect, x_mat, id_vect, beta_hat_R, fold, p, lam_vect, eps_stop, iter_try, corr_str) {
    .Call('PGS_est_pgee_grid_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, beta_hat_R, fold, p, lam_vect, eps_stop, iter_try, corr_str)
}

one_run_grid_cpp <- function(y_vect, x_mat, id_vect, beta_ini, fold, p, lam_vect, eps_stop, iter_try, corr_str) {
    .Call('PGS_one_run_grid_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, beta_ini, fold, p, lam_vect, eps_stop, iter_try, corr_str)
}

indGen_cpp <- function(id_vect) {
    .Call('PGS_indGen_cpp', PACKAGE = 'PGS', id_vect)
}

