# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

q_scad_cpp <- function(theta, lambda, a) {
    .Call('PGS_q_scad_cpp', PACKAGE = 'PGS', theta, lambda, a)
}

S_H_E_normal_cpp <- function(y_vect, x_mat, id_vect, hat_R, beta_val, n, m, lam, eps) {
    .Call('PGS_S_H_E_normal_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, hat_R, beta_val, n, m, lam, eps)
}

beta_shrink_normal_cpp <- function(y_vect, x_mat, id_vect, hat_R, beta_ini, n, m, lam, eps, eps_stop, max_step) {
    .Call('PGS_beta_shrink_normal_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, hat_R, beta_ini, n, m, lam, eps, eps_stop, max_step)
}

CV_lam_grid_cpp <- function(y_vect, x_mat, id_vect, hat_R, beta_ini, n, m, fold, lam_vect, eps, eps_stop, max_step) {
    .Call('PGS_CV_lam_grid_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, hat_R, beta_ini, n, m, fold, lam_vect, eps, eps_stop, max_step)
}

est_pgee_grid_cpp <- function(y_vect, x_mat, id_vect, hat_R, beta_ini, n, m, fold, lam_vect, eps, eps_stop, max_step) {
    .Call('PGS_est_pgee_grid_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, hat_R, beta_ini, n, m, fold, lam_vect, eps, eps_stop, max_step)
}

corr_est_normal_cpp <- function(y_vect, x_mat, id_vect, beta_val, n, m, corr_str) {
    .Call('PGS_corr_est_normal_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, beta_val, n, m, corr_str)
}

one_run_grid_cpp <- function(y_vect, x_mat, id_vect, n, m, pn, fold, lam_vect, rho, eps, eps_stop, max_step, corr_str) {
    .Call('PGS_one_run_grid_cpp', PACKAGE = 'PGS', y_vect, x_mat, id_vect, n, m, pn, fold, lam_vect, rho, eps, eps_stop, max_step, corr_str)
}

